//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medalist
    {
        public int MedalistID { get; set; }
        public string Event { get; set; }
        public Nullable<int> Edition { get; set; }
        public string Athlete { get; set; }
        public string NOC { get; set; }
        public string Gender { get; set; }
        public string Medal { get; set; }
        public string Season { get; set; }
        public Nullable<double> MedalValue { get; set; }
        public Nullable<int> DisciplineID { get; set; }
        public Nullable<int> SportID { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
